### ISSUE TITLE
Crash with CarAccident3

### ISSUE THREAD

**Issue by SuperPyroManiac** [SuperPyroManiac/SuperPlugins#21]
Related to the injured animation most likely.
[RagePluginHook (1).log](https://github.com/SuperPyroManiac/SuperPlugins/files/7197899/RagePluginHook.1.log)

```
[9/18/2021 2:15:00 PM.113] LSPD First Response: ==============================
[9/18/2021 2:15:00 PM.113] LSPD First Response: UNHANDLED EXCEPTION DURING GAME FIBER TICK
[9/18/2021 2:15:00 PM.113] LSPD First Response: ------------------------------
[9/18/2021 2:15:00 PM.113] LSPD First Response: Origin: Game fiber "<UNNAMED THREAD>".
[9/18/2021 2:15:00 PM.113] LSPD First Response: ------------------------------
[9/18/2021 2:15:00 PM.113] LSPD First Response: Exception type: System.InvalidOperationException
[9/18/2021 2:15:00 PM.113] LSPD First Response: Exception message: AnimationSet "move_injured_ground" could not be loaded within a reasonable time. It may be invalid.
[9/18/2021 2:15:00 PM.113] LSPD First Response: ------------------------------
[9/18/2021 2:15:00 PM.113] LSPD First Response: Inner exceptions:
[9/18/2021 2:15:00 PM.113] LSPD First Response: ------------------------------
[9/18/2021 2:15:00 PM.113] LSPD First Response: Stack trace:
[9/18/2021 2:15:00 PM.113] LSPD First Response: at AssetHelper.WaitForAssetLoad(IAsset asset, String assetTypeName)
[9/18/2021 2:15:00 PM.113] at Rage.AnimationSet.LoadAndWait()
[9/18/2021 2:15:00 PM.113] at SuperCallouts2.SimpleFunctions.CFunctions.<>c__DisplayClass6_0.<SetAnimation>b__0()
[9/18/2021 2:15:00 PM.113] at Rage.GameFiber.Main()
[9/18/2021 2:15:00 PM.113] LSPD First Response: ==============================
[9/18/2021 2:15:00 PM.113] LSPD First Response: 
[9/18/2021 2:15:00 PM.115] LSPD First Response: [FATAL] Forced termination
```

**Comment by SuperPyroManiac** [comment]
Seems to have solved itself with some sort of black magic.
